In [1]:
import pandas as pd

In [27]:
df = pd.read_csv("../data/autumn_courses_raw.csv")

In [28]:
for col in df.columns:
    print(col)

Unnamed: 0
crsecode
crsename
totcred
crsetype
lecture
tutorial
practical
selfstudy
crseduration
prereq
homepage
textref
description
springcourse
springinstructor
autumncourse
autumninstructor
slot
offered
date
year

In [29]:
df.head()

,Unnamed: 0,crsecode,crsename,totcred,crsetype,lecture,tutorial,practical,selfstudy,crseduration,...,textref,description,springcourse,springinstructor,autumncourse,autumninstructor,slot,offered,date,year
0,0,CS 101,Computer Programming and Utilization,6,Theory + Lab,2,0,2,0,Full Semester,...,<b>Textbook</b><br/>\r\n<ul>\r\n <li>* C++ ...,This course provides an introduction to proble...,True,Prof. Vinay J. Ribeiro,True,Prof. Abir De,-1,True,2026-06-22T13:41:53.498830+05:30,0
1,1,CS 105,Discrete Structures,6,NaN,0,0,0,0,NaN,...,"1. Kenneth Rosen, Discrete Mathematics and its...","Propositions and predicates, proofs and proof ...",False,Prof. Akshay S,True,Prof. Bharat Adsul,-1,True,2026-06-18T11:50:41.393755+05:30,0
2,2,CS 213,Data Structures and Algorithms,6,Theory,0,0,0,0,Full Semester,...,"1. T. Cormen, C. Leiserson, R. Rivest, C. Stei...","Introduction to data structures, abstract data...",False,NaN,True,Prof. Manoj Prabhakaran,-1,True,2026-06-18T11:52:05.109556+05:30,0
3,3,CS 215,Data Analysis and Interpretation,6,NaN,3,0,0,0,NaN,...,Course textbook: Introduction to Probability a...,See course home page below.,False,NaN,True,Prof. Sharat Chandran,3,True,2026-06-18T11:53:25.322327+05:30,0
4,4,CS 228,Logic For CS,6,Theory,0,0,0,0,Full Semester,...,Logic in Computer Science. Huth and Ryan.Cambr...,1 Propositional logic:<br/>\r\n1.1 Declarative...,False,Prof. Krishna S,True,Prof. S. Akshay,-1,True,2026-06-18T11:54:29.290091+05:30,0

In [30]:
df["year"] = pd.to_datetime(df["date"]).dt.year

In [31]:
df = df[["crsecode", "crsename", "autumncourse", "autumninstructor", "offered", "year"]]

In [32]:
df.head()

,crsecode,crsename,autumncourse,autumninstructor,offered,year
0,CS 101,Computer Programming and Utilization,True,Prof. Abir De,True,2026
1,CS 105,Discrete Structures,True,Prof. Bharat Adsul,True,2026
2,CS 213,Data Structures and Algorithms,True,Prof. Manoj Prabhakaran,True,2026
3,CS 215,Data Analysis and Interpretation,True,Prof. Sharat Chandran,True,2026
4,CS 228,Logic For CS,True,Prof. S. Akshay,True,2026